/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.uno;

import Pile.*;
import Player.Player;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author ujjwaljain
 */
public class InitializePlayers extends javax.swing.JFrame {

    /**
     * Creates new form InitializePlayers
     */
    public ArrayList<String> pnames;
    public ArrayList<Player> players ;
    public DrawPile drawPile;
    public DiscardPile discardPile;

    public InitializePlayers(){
        initComponents();
        pnames=new ArrayList<>();
    }
    
    public InitializePlayers(ArrayList<Player> players,DrawPile drawPile,DiscardPile discardPile) {
        initComponents();
        pnames=new ArrayList<>();
        this.players = players;
        this.drawPile=drawPile;
        this.discardPile=discardPile;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Players = new javax.swing.JLabel();
        PlayerName = new javax.swing.JTextField();
        Save = new javax.swing.JButton();
        Start = new javax.swing.JButton();
        p3name = new javax.swing.JLabel();
        p2name = new javax.swing.JLabel();
        p1name = new javax.swing.JLabel();
        p4name = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Players.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        Players.setText("Players");

        PlayerName.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        PlayerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayerNameActionPerformed(evt);
            }
        });

        Save.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        Start.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        Start.setText("Start");
        Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartActionPerformed(evt);
            }
        });

        p3name.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N

        p2name.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N

        p1name.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N

        p4name.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(PlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Players)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(p3name, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(142, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(p4name, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p2name, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(168, 168, 168))
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Start, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(109, 109, 109)
                    .addComponent(p1name, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(425, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(Players)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(p2name, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p3name, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p4name, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Start, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(273, Short.MAX_VALUE)
                    .addComponent(p1name, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(187, 187, 187)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public ArrayList<Player> getPlayers(){
        return players;
    }
    
    private void PlayerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlayerNameActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        if(PlayerName.getText().isEmpty()){
            JLabel message = new JLabel("Please Enter Player Name");
            message.setFont(new Font("Arial",Font.BOLD,36));
            JOptionPane.showMessageDialog(null, message);
        }
        else{
            String name = PlayerName.getText().trim();
            pnames.add(name);
            if(pnames.size()>0 && pnames.size()<5){
                JLabel message = new JLabel("Player Name Saved! ");
                message.setFont(new Font("Arial",Font.BOLD,36));
                JOptionPane.showMessageDialog(null, message);
                PlayerName.setText("");
                if(pnames.size()==1)
                    p1name.setText(pnames.get(0));
                else if (pnames.size()==2){
                    p1name.setText(pnames.get(0));
                    p2name.setText(pnames.get(1));
                }
                else if(pnames.size()==3){
                    p1name.setText(pnames.get(0));
                    p2name.setText(pnames.get(1));
                    p3name.setText(pnames.get(2));
                }
                else if (pnames.size()==4){
                    p1name.setText(pnames.get(0));
                    p2name.setText(pnames.get(1));
                    p3name.setText(pnames.get(2));
                    p4name.setText(pnames.get(3));
                }
            }
            if(pnames.size()>=5){
                pnames.remove(4);
                JLabel message = new JLabel("Player Limit Exceeded! ");
                message.setFont(new Font("Arial",Font.BOLD,36));
                JOptionPane.showMessageDialog(null, message);
                PlayerName.setText("");
            }
        }
    }//GEN-LAST:event_SaveActionPerformed

    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed
        if(pnames.size()!=4){
            JLabel message = new JLabel("Please Enter 4 Players ");
            message.setFont(new Font("Arial",Font.BOLD,36));
            JOptionPane.showMessageDialog(null, message);
        }
        else{
            for(int i =0;i<4;i++){
                players.add(new Player(pnames.get(i),i+1,discardPile,drawPile));}
            this.dispose();
//            new Game(players,discardPile,drawPile).setVisible(true);
        }
    }//GEN-LAST:event_StartActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InitializePlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InitializePlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InitializePlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InitializePlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InitializePlayers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PlayerName;
    private javax.swing.JLabel Players;
    private javax.swing.JButton Save;
    private javax.swing.JButton Start;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel p1name;
    private javax.swing.JLabel p2name;
    private javax.swing.JLabel p3name;
    private javax.swing.JLabel p4name;
    // End of variables declaration//GEN-END:variables
}
